name: camera_android_camerax
description: Android implementation of the camera plugin using the CameraX library.

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

flutter:
  plugin:
    implements: camera
    platforms:
      android:
        package: io.flutter.plugins.camerax
        pluginClass: CameraAndroidCameraxPlugin
        dartPluginClass: AndroidCameraCameraX

dependencies:
  async: ^2.5.0
  camera_platform_interface: ^2.6.0
  flutter:
    sdk: flutter
  meta: ^1.7.0
  stream_transform: ^2.1.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: 5.4.4
  pigeon: ^9.1.0

topics:
  - camera
